ISO_639_1: dict[str, str | None] = {
    'aa': None,
    'ab': None,
    'ae': None,
    'af': None,
    'ak': None,
    'am': None,
    'an': None,
    'ar': None,
    'as': None,
    'av': None,
    'ay': None,
    'az': None,
    'ba': None,
    'be': None,
    'bg': None,
    'bh': None,
    'bi': None,
    'bm': None,
    'bn': None,
    'bo': None,
    'br': None,
    'bs': None,
    'ca': None,
    'ce': None,
    'ch': None,
    'co': None,
    'cr': None,
    'cs': None,
    'cu': None,
    'cv': None,
    'cy': None,
    'da': None,
    'de': None,
    'dv': None,
    'dz': None,
    'ee': None,
    'el': None,
    'en': None,
    'eo': None,
    'es': None,
    'et': None,
    'eu': None,
    'fa': None,
    'ff': None,
    'fi': None,
    'fj': None,
    'fo': None,
    'fr': None,
    'fy': None,
    'ga': None,
    'gd': None,
    'gl': None,
    'gn': None,
    'gu': None,
    'gv': None,
    'ha': None,
    'he': None,
    'hi': None,
    'ho': None,
    'hr': None,
    'ht': None,
    'hu': None,
    'hy': None,
    'hz': None,
    'ia': None,
    'id': None,
    'ie': None,
    'ig': None,
    'ii': None,
    'ik': None,
    'io': None,
    'is': None,
    'it': None,
    'iu': None,
    'ja': None,
    'jv': None,
    'ka': None,
    'kg': None,
    'ki': None,
    'kj': None,
    'kk': None,
    'kl': None,
    'km': None,
    'kn': None,
    'ko': None,
    'kr': None,
    'ks': None,
    'ku': None,
    'kv': None,
    'kw': None,
    'ky': None,
    'la': None,
    'lb': None,
    'lg': None,
    'li': None,
    'ln': None,
    'lo': None,
    'lt': None,
    'lu': None,
    'lv': None,
    'mg': None,
    'mh': None,
    'mi': None,
    'mk': None,
    'ml': None,
    'mn': None,
    'mr': None,
    'ms': None,
    'mt': None,
    'my': None,
    'na': None,
    'nb': None,
    'nd': None,
    'ne': None,
    'ng': None,
    'nl': None,
    'nn': None,
    'no': None,
    'nr': None,
    'nv': None,
    'ny': None,
    'oc': None,
    'oj': None,
    'om': None,
    'or': None,
    'os': None,
    'pa': None,
    'pi': None,
    'pl': None,
    'ps': None,
    'pt': None,
    'qu': None,
    'rm': None,
    'rn': None,
    'ro': None,
    'ru': None,
    'rw': None,
    'sa': None,
    'sc': None,
    'sd': None,
    'se': None,
    'sg': None,
    'si': None,
    'sk': None,
    'sl': None,
    'sm': None,
    'sn': None,
    'so': None,
    'sq': None,
    'sr': None,
    'ss': None,
    'st': None,
    'su': None,
    'sv': None,
    'sw': None,
    'ta': None,
    'te': None,
    'tg': None,
    'th': None,
    'ti': None,
    'tk': None,
    'tl': None,
    'tn': None,
    'to': None,
    'tr': None,
    'ts': None,
    'tt': None,
    'tw': None,
    'ty': None,
    'ug': None,
    'uk': None,
    'ur': None,
    'uz': None,
    've': None,
    'vi': None,
    'vo': None,
    'wa': None,
    'wo': None,
    'xh': None,
    'yi': None,
    'yo': None,
    'za': None,
    'zh': None,
    'zu': None
}

ISO_3166: set[str] = {
    'GG', 'GI', 'JO', 'NO', 'BH', 'TT', 'BA', 'OM', 'UY', 'MR', 'GP', 'MU',
    'BR', 'NU', 'ML', 'TC', 'MZ', 'GY', 'KI', 'BJ', 'CA', 'AG', 'GN', 'IO',
    'ST', 'LV', 'NZ', 'LA', 'EH', 'DO', 'VE', 'TF', 'FM', 'AD', 'SI', 'GQ',
    'AQ', 'VG', 'CR', 'SK', 'NC', 'TZ', 'TK', 'ER', 'CV', 'IL', 'SO', 'AS',
    'RW', 'MX', 'SA', 'AM', 'VA', 'GF', 'HM', 'PT', 'LC', 'MS', 'VU', 'BS',
    'AW', 'SV', 'KZ', 'DJ', 'QA', 'AE', 'PH', 'BV', 'HU', 'LK', 'GU', 'BD',
    'AL', 'CK', 'RU', 'MK', 'AT', 'KY', 'TV', 'GH', 'KN', 'PK', 'MM', 'VI',
    'WF', 'AI', 'BF', 'KP', 'YT', 'ES', 'KM', 'FI', 'PY', 'RO', 'IE', 'AU',
    'AO', 'IM', 'BG', 'SC', 'BN', 'PF', 'HR', 'GA', 'EE', 'AR', 'SZ', 'DE',
    'ZM', 'CF', 'HK', 'BB', 'EC', 'SG', 'DZ', 'IR', 'SY', 'CD', 'LU', 'DM',
    'MH', 'US', 'BE', 'GL', 'CH', 'MF', 'PE', 'NE', 'CM', 'CX', 'GB', 'PR',
    'MW', 'SD', 'MC', 'LR', 'MY', 'MQ', 'MO', 'BT', 'NI', 'PG', 'MA', 'TN',
    'SE', 'NR', 'LY', 'FK', 'TL', 'JM', 'IT', 'CC', 'BY', 'GM', 'HT', 'TD',
    'PN', 'JP', 'WS', 'ZA', 'YE', 'FJ', 'CU', 'ZW', 'PW', 'SR', 'TG', 'FO',
    'UG', 'BI', 'ET', 'BL', 'UA', 'GT', 'VN', 'PM', 'LT', 'VC', 'GW', 'SJ',
    'SM', 'TW', 'TR', 'MG', 'ID', 'AX', 'RS', 'LB', 'CO', 'PA', 'TJ', 'AZ',
    'JE', 'UM', 'CZ', 'CG', 'UZ', 'SN', 'TH', 'CN', 'IS', 'NG', 'NF', 'KH',
    'DK', 'KW', 'ME', 'SL', 'NA', 'KE', 'PS', 'TM', 'HN', 'SH', 'TO', 'EG',
    'CY', 'GD', 'CI', 'GR', 'LS', 'NL', 'CL', 'AN', 'AF', 'MV', 'GS', 'NP',
    'MD', 'GE', 'MN', 'MP', 'IQ', 'KR', 'PL', 'BO', 'BZ', 'IN', 'BW', 'MT',
    'SB', 'FR', 'RE', 'BM', 'KG', 'LI'
}

ISO_4217: set[str] = {
    'CHC', 'AUD', 'ADP', 'BWP', 'LRD', 'SSP', 'TND', 'GWP', 'TMT', 'SRD', 'CNY',
    'BYB', 'CHW', 'SEK', 'XFU', 'BGN', 'UGW', 'RSD', 'KRW', 'BOB', 'TPE', 'YER',
    'ILR', 'ALK', 'LAJ', 'MUR', 'VUV', 'ANG', 'XRE', 'DZD', 'SRG', 'SIT', 'TTD',
    'XCD', 'BND', 'ZWG', 'GQE', 'GEL', 'AZN', 'BRB', 'RWF', 'USS', 'MVR', 'RUR',
    'LSL', 'HTG', 'HKD', 'LUF', 'BOP', 'PYG', 'IEP', 'XAU', 'XPF', 'SDP', 'CLP',
    'XBA', 'GEK', 'UAK', 'GNE', 'BHD', 'CYP', 'SZL', 'BBD', 'EGP', 'VES', 'SDD',
    'XBD', 'ZWL', 'VEB', 'BIF', 'GHS', 'LYD', 'CRC', 'COU', 'AOK', 'MOP', 'XTS',
    'GNS', 'MZE', 'PKR', 'UYW', 'YUD', 'MRO', 'PTE', 'CZK', 'BRR', 'NAD', 'VND',
    'KGS', 'UGX', 'KZT', 'XBB', 'ISJ', 'CVE', 'GYD', 'CSD', 'KMF', 'SOS', 'DOP',
    'VED', 'NGN', 'UZS', 'CSK', 'NZD', 'LAK', 'BYN', 'BSD', 'ARP', 'MDL', 'RUB',
    'KWD', 'BDT', 'JOD', 'AZM', 'MWK', 'BAD', 'ILS', 'ZAL', 'TZS', 'ESA', 'TRL',
    'GRD', 'ATS', 'IQD', 'ROL', 'ZWR', 'CUC', 'RON', 'HNL', 'AED', 'UYN', 'UYI',
    'BUK', 'JMD', 'KES', 'AON', 'BOV', 'BGK', 'SBD', 'BGL', 'GTQ', 'SVC', 'XFO',
    'ETB', 'AMD', 'ZRN', 'VNC', 'GNF', 'LVL', 'TJS', 'AFN', 'PLN', 'STN', 'MKD',
    'UYP', 'MVQ', 'CLF', 'SLL', 'ALL', 'GHC', 'DEM', 'MXN', 'AOA', 'XOF', 'USD',
    'EUR', 'SAR', 'TRY', 'XPD', 'CAD', 'IDR', 'CHE', 'UAH', 'GMD', 'ITL', 'MMK',
    'ZAR', 'STD', 'ZMK', 'QAR', 'XSU', 'DDM', 'TWD', 'XBC', 'MYR', 'ZWC', 'LSM',
    'SLE', 'KPW', 'TJR', 'ESB', 'GWE', 'YUN', 'WST', 'MZN', 'UYU', 'SCR', 'ZMW',
    'COP', 'XPT', 'CHF', 'HRD', 'ERN', 'BRE', 'ZWN', 'ROK', 'PES', 'SUR', 'PEN',
    'XXX', 'CUP', 'LTL', 'TMM', 'CSJ', 'PEH', 'SDG', 'DJF', 'NIC', 'LKR', 'AFA',
    'PEI', 'UGS', 'NOK', 'IRR', 'PLZ', 'ECV', 'NIO', 'THB', 'YUM', 'XDR', 'XAF',
    'MAD', 'VEF', 'BGJ', 'EEK', 'BEF', 'ZWD', 'MTP', 'ECS', 'BZD', 'MXV', 'ARY',
    'MLF', 'SGD', 'SKK', 'PGK', 'XEU', 'BRL', 'LUC', 'FKP', 'BRC', 'KYD', 'HUF',
    'ARS', 'XAG', 'MNT', 'BEC', 'SYP', 'XUA', 'BYR', 'OMR', 'MGA', 'FRF', 'XCG',
    'NLG', 'AOR', 'TOP', 'BEL', 'FIM', 'MZM', 'LVR', 'JPY', 'ARA', 'USN', 'LUL',
    'MGF', 'BMD', 'ILP', 'YDD', 'DKK', 'LTT', 'INR', 'RHD', 'BTN', 'NPR', 'AYM',
    'KHR', 'MTL', 'PAB', 'BAM', 'GIP', 'FJD', 'MRU', 'BRN', 'AWG', 'CDF', 'MXP',
    'LBP', 'ISK', 'PHP', 'ZRZ', 'HRK', 'GBP', 'GHP', 'ESP', 'SHP'
}
