ISO_639_1: dict[str, str] = {
    'aa': '',
    'ab': '',
    'ae': '',
    'af': '',
    'ak': '',
    'am': '',
    'an': '',
    'ar': '',
    'as': '',
    'av': '',
    'ay': '',
    'az': '',
    'ba': '',
    'be': '',
    'bg': 'абвгдежзийклмнопрстуфхцчшщъьюя',
    'bh': '',
    'bi': '',
    'bm': '',
    'bn': '',
    'bo': '',
    'br': '',
    'bs': '',
    'ca': '',
    'ce': '',
    'ch': '',
    'co': '',
    'cr': '',
    'cs': 'áčďéěíňóřšťúůýž',
    'cu': '',
    'cv': '',
    'cy': '',
    'da': 'æøåÆØÅ',
    'de': 'äöüßÄÖÜ',
    'dv': '',
    'dz': '',
    'ee': '',
    'el': 'αβγδεζηθικλμνξοπρστυφχψωάέήίόύώϊϋΐΰ',
    'en': '',
    'eo': '',
    'es': 'áéíóúüñ',
    'et': 'äöüõ',
    'eu': '',
    'fa': '',
    'ff': '',
    'fi': 'äö',
    'fj': '',
    'fo': '',
    'fr': 'éàèùâêîôûëïüçœ',
    'fy': '',
    'ga': 'áéíóú',
    'gd': '',
    'gl': '',
    'gn': '',
    'gu': '',
    'gv': '',
    'ha': '',
    'he': '',
    'hi': '',
    'ho': '',
    'hr': 'čćđšž',
    'ht': '',
    'hu': 'áéíóöőúüű',
    'hy': '',
    'hz': '',
    'ia': '',
    'id': '',
    'ie': '',
    'ig': '',
    'ii': '',
    'ik': '',
    'io': '',
    'is': 'áéíóúýþæöð',
    'it': 'àèéìòóù',
    'iu': '',
    'ja': '',
    'jv': '',
    'ka': '',
    'kg': '',
    'ki': '',
    'kj': '',
    'kk': '',
    'kl': '',
    'km': '',
    'kn': '',
    'ko': '',
    'kr': '',
    'ks': '',
    'ku': '',
    'kv': '',
    'kw': '',
    'ky': '',
    'la': '',
    'lb': '',
    'lg': '',
    'li': '',
    'ln': '',
    'lo': '',
    'lt': 'ąčęėįšųūž',
    'lu': '',
    'lv': 'āčēģīķļņšūž',
    'mg': '',
    'mh': '',
    'mi': '',
    'mk': '',
    'ml': '',
    'mn': '',
    'mr': '',
    'ms': '',
    'mt': 'ċġħżàèìòù',
    'my': '',
    'na': '',
    'nb': '',
    'nd': '',
    'ne': '',
    'ng': '',
    'nl': 'éëïóöü',
    'nn': '',
    'no': 'æøå',
    'nr': '',
    'nv': '',
    'ny': '',
    'oc': '',
    'oj': '',
    'om': '',
    'or': '',
    'os': '',
    'pa': '',
    'pi': '',
    'pl': 'ąćęłńóśźż',
    'ps': '',
    'pt': 'áâãàçéêíóôõú',
    'qu': '',
    'rm': '',
    'rn': '',
    'ro': 'ăâîșț',
    'ru': '',
    'rw': '',
    'sa': '',
    'sc': '',
    'sd': '',
    'se': '',
    'sg': '',
    'si': '',
    'sk': 'áäčďéíĺľňóôŕšťúýž',
    'sl': 'čšž',
    'sm': '',
    'sn': '',
    'so': '',
    'sq': '',
    'sr': '',
    'ss': '',
    'st': '',
    'su': '',
    'sv': 'åäö',
    'sw': '',
    'ta': '',
    'te': '',
    'tg': '',
    'th': '',
    'ti': '',
    'tk': '',
    'tl': '',
    'tn': '',
    'to': '',
    'tr': '',
    'ts': '',
    'tt': '',
    'tw': '',
    'ty': '',
    'ug': '',
    'uk': '',
    'ur': '',
    'uz': '',
    've': '',
    'vi': '',
    'vo': '',
    'wa': '',
    'wo': '',
    'xh': '',
    'yi': '',
    'yo': '',
    'za': '',
    'zh': '',
    'zu': ''
}

ISO_3166: set[str] = {
    'GG', 'GI', 'JO', 'NO', 'BH', 'TT', 'BA', 'OM', 'UY', 'MR', 'GP', 'MU',
    'BR', 'NU', 'ML', 'TC', 'MZ', 'GY', 'KI', 'BJ', 'CA', 'AG', 'GN', 'IO',
    'ST', 'LV', 'NZ', 'LA', 'EH', 'DO', 'VE', 'TF', 'FM', 'AD', 'SI', 'GQ',
    'AQ', 'VG', 'CR', 'SK', 'NC', 'TZ', 'TK', 'ER', 'CV', 'IL', 'SO', 'AS',
    'RW', 'MX', 'SA', 'AM', 'VA', 'GF', 'HM', 'PT', 'LC', 'MS', 'VU', 'BS',
    'AW', 'SV', 'KZ', 'DJ', 'QA', 'AE', 'PH', 'BV', 'HU', 'LK', 'GU', 'BD',
    'AL', 'CK', 'RU', 'MK', 'AT', 'KY', 'TV', 'GH', 'KN', 'PK', 'MM', 'VI',
    'WF', 'AI', 'BF', 'KP', 'YT', 'ES', 'KM', 'FI', 'PY', 'RO', 'IE', 'AU',
    'AO', 'IM', 'BG', 'SC', 'BN', 'PF', 'HR', 'GA', 'EE', 'AR', 'SZ', 'DE',
    'ZM', 'CF', 'HK', 'BB', 'EC', 'SG', 'DZ', 'IR', 'SY', 'CD', 'LU', 'DM',
    'MH', 'US', 'BE', 'GL', 'CH', 'MF', 'PE', 'NE', 'CM', 'CX', 'GB', 'PR',
    'MW', 'SD', 'MC', 'LR', 'MY', 'MQ', 'MO', 'BT', 'NI', 'PG', 'MA', 'TN',
    'SE', 'NR', 'LY', 'FK', 'TL', 'JM', 'IT', 'CC', 'BY', 'GM', 'HT', 'TD',
    'PN', 'JP', 'WS', 'ZA', 'YE', 'FJ', 'CU', 'ZW', 'PW', 'SR', 'TG', 'FO',
    'UG', 'BI', 'ET', 'BL', 'UA', 'GT', 'VN', 'PM', 'LT', 'VC', 'GW', 'SJ',
    'SM', 'TW', 'TR', 'MG', 'ID', 'AX', 'RS', 'LB', 'CO', 'PA', 'TJ', 'AZ',
    'JE', 'UM', 'CZ', 'CG', 'UZ', 'SN', 'TH', 'CN', 'IS', 'NG', 'NF', 'KH',
    'DK', 'KW', 'ME', 'SL', 'NA', 'KE', 'PS', 'TM', 'HN', 'SH', 'TO', 'EG',
    'CY', 'GD', 'CI', 'GR', 'LS', 'NL', 'CL', 'AN', 'AF', 'MV', 'GS', 'NP',
    'MD', 'GE', 'MN', 'MP', 'IQ', 'KR', 'PL', 'BO', 'BZ', 'IN', 'BW', 'MT',
    'SB', 'FR', 'RE', 'BM', 'KG', 'LI'
}

ISO_4217: set[str] = {
    'CHC', 'AUD', 'ADP', 'BWP', 'LRD', 'SSP', 'TND', 'GWP', 'TMT', 'SRD', 'CNY',
    'BYB', 'CHW', 'SEK', 'XFU', 'BGN', 'UGW', 'RSD', 'KRW', 'BOB', 'TPE', 'YER',
    'ILR', 'ALK', 'LAJ', 'MUR', 'VUV', 'ANG', 'XRE', 'DZD', 'SRG', 'SIT', 'TTD',
    'XCD', 'BND', 'ZWG', 'GQE', 'GEL', 'AZN', 'BRB', 'RWF', 'USS', 'MVR', 'RUR',
    'LSL', 'HTG', 'HKD', 'LUF', 'BOP', 'PYG', 'IEP', 'XAU', 'XPF', 'SDP', 'CLP',
    'XBA', 'GEK', 'UAK', 'GNE', 'BHD', 'CYP', 'SZL', 'BBD', 'EGP', 'VES', 'SDD',
    'XBD', 'ZWL', 'VEB', 'BIF', 'GHS', 'LYD', 'CRC', 'COU', 'AOK', 'MOP', 'XTS',
    'GNS', 'MZE', 'PKR', 'UYW', 'YUD', 'MRO', 'PTE', 'CZK', 'BRR', 'NAD', 'VND',
    'KGS', 'UGX', 'KZT', 'XBB', 'ISJ', 'CVE', 'GYD', 'CSD', 'KMF', 'SOS', 'DOP',
    'VED', 'NGN', 'UZS', 'CSK', 'NZD', 'LAK', 'BYN', 'BSD', 'ARP', 'MDL', 'RUB',
    'KWD', 'BDT', 'JOD', 'AZM', 'MWK', 'BAD', 'ILS', 'ZAL', 'TZS', 'ESA', 'TRL',
    'GRD', 'ATS', 'IQD', 'ROL', 'ZWR', 'CUC', 'RON', 'HNL', 'AED', 'UYN', 'UYI',
    'BUK', 'JMD', 'KES', 'AON', 'BOV', 'BGK', 'SBD', 'BGL', 'GTQ', 'SVC', 'XFO',
    'ETB', 'AMD', 'ZRN', 'VNC', 'GNF', 'LVL', 'TJS', 'AFN', 'PLN', 'STN', 'MKD',
    'UYP', 'MVQ', 'CLF', 'SLL', 'ALL', 'GHC', 'DEM', 'MXN', 'AOA', 'XOF', 'USD',
    'EUR', 'SAR', 'TRY', 'XPD', 'CAD', 'IDR', 'CHE', 'UAH', 'GMD', 'ITL', 'MMK',
    'ZAR', 'STD', 'ZMK', 'QAR', 'XSU', 'DDM', 'TWD', 'XBC', 'MYR', 'ZWC', 'LSM',
    'SLE', 'KPW', 'TJR', 'ESB', 'GWE', 'YUN', 'WST', 'MZN', 'UYU', 'SCR', 'ZMW',
    'COP', 'XPT', 'CHF', 'HRD', 'ERN', 'BRE', 'ZWN', 'ROK', 'PES', 'SUR', 'PEN',
    'XXX', 'CUP', 'LTL', 'TMM', 'CSJ', 'PEH', 'SDG', 'DJF', 'NIC', 'LKR', 'AFA',
    'PEI', 'UGS', 'NOK', 'IRR', 'PLZ', 'ECV', 'NIO', 'THB', 'YUM', 'XDR', 'XAF',
    'MAD', 'VEF', 'BGJ', 'EEK', 'BEF', 'ZWD', 'MTP', 'ECS', 'BZD', 'MXV', 'ARY',
    'MLF', 'SGD', 'SKK', 'PGK', 'XEU', 'BRL', 'LUC', 'FKP', 'BRC', 'KYD', 'HUF',
    'ARS', 'XAG', 'MNT', 'BEC', 'SYP', 'XUA', 'BYR', 'OMR', 'MGA', 'FRF', 'XCG',
    'NLG', 'AOR', 'TOP', 'BEL', 'FIM', 'MZM', 'LVR', 'JPY', 'ARA', 'USN', 'LUL',
    'MGF', 'BMD', 'ILP', 'YDD', 'DKK', 'LTT', 'INR', 'RHD', 'BTN', 'NPR', 'AYM',
    'KHR', 'MTL', 'PAB', 'BAM', 'GIP', 'FJD', 'MRU', 'BRN', 'AWG', 'CDF', 'MXP',
    'LBP', 'ISK', 'PHP', 'ZRZ', 'HRK', 'GBP', 'GHP', 'ESP', 'SHP'
}
